### PR TITLE
bring SPM branch forward to master

### PR DESCRIPTION
**Pull request by jarrodparkes**
in lieu of SPM support, this brings SPM branch forward to master

### CODE REVIEW

**Comment by jarrodparkes** [comment]
@bannzai not sure what else this is waiting on to become part of `master` but this is just for bringing the existing `spm` branch up to HEAD

**Comment by jawi-bq** [comment]
What is this PR waiting for?

**Comment by rogerluan** [comment]
Friendly ping @bannzai ? 🙏

**Comment by packatino** [comment]
Any updates here? Can someone merge this PR? I would really like to use SpreadsheetView with SPM 🙏

**Comment by PorterHoskins** [comment]
Anything we can do to help this along?

**Pull request closed without merging**
