### PR TITLE
whole lotta refactoring

### PR DESCRIPTION
**Pull request by adamnemecek**

### CODE REVIEW

**Comment by kishikawakatsumi** [comment]
@adamnemecek Could you explain? You also broke a lot of tests.

**Comment by adamnemecek** [comment]
It's all refactoring. The build Break isn't due to me.

**Comment by kishikawakatsumi** [comment]
@adamnemecek It seems obvious you broke some tests https://travis-ci.org/kishikawakatsumi/SpreadsheetView/builds/259969071?utm_source=github_status&utm_medium=notification. Could you make sure the tests passing before submitting PR? I cannot merge this PR until you fix them. Also, I recommend split each commit into multiple smaller PRs.

**Comment by kishikawakatsumi** [comment]
@adamnemecek I cannot merge this because the changes break existing behavior. But that’s really helpful each change. Thanks for contributing!

**Pull request closed without merging**
