### PR TITLE
update Swift 5

### PR DESCRIPTION
**Pull request by 0xGareth**
I have updated project swift version to 5.0 from 3.0 on Xcode 10.2

When I tested project with Xcode 10.2 with iPhone XR 12.2 Simulator on test failured.

Failure Detailes.
Failured Location : Viewtests - testEmbedInNavigationController L144
Failured Test Code : XCTAssertEqual(spreadsheetView.adjustedContentInset.bottom, 0)
Result : XCTAssertEqual failed: ("34.0") is not equal to ("0.0") -

so, i changed the code with
Code: XCTAssertEqual(spreadsheetView.adjustedContentInset.bottom, viewController.view.safeAreaInsets.bottom)

all test passed on Xcode 10.2 with iPhone 7 (iOS 12.2) and iPhone Xr.

### CODE REVIEW

**Comment by umverteiler** [comment]
Any news on this PR?

**Comment by hlongvu** [comment]
Any update on this pr?

**Comment by dillan** [comment]
@kishikawakatsumi How can we help push this forward? Thanks @Widehuang!

**Comment by bannzai** [comment]
Done about up swift version to 5. I will release it. I close this PR. Thank you your contributions 👍 

https://github.com/bannzai/SpreadsheetView/pull/256

**Pull request closed without merging**
