### PR TITLE
Fix content offset jumps after reloading

### PR DESCRIPTION
**Pull request by kishikawakatsumi**
Fixes https://github.com/kishikawakatsumi/SpreadsheetView/issues/110

### CODE REVIEW

**Comment by muratmusic** [comment]
Hello @kishikawakatsumi

Thank you very much. I cannot reproduce this bug at the moment after checkout fix-jump-on-reload branch.

Many thanks!

**Comment by muratmusic** [comment]
It looks strange but I cannot scroll SpreadsheetView on my app after I checkout fix-jump-on-reload branch. Probably because I add SpreadsheetView as UIView on storyboard. SpreadsheetView on my app can be scrolled with master branch (with scroll-position bug).

Demo apps look great if I checkout fix-jump-on-reload branch.

**Comment by kishikawakatsumi** [comment]
@muratmusic Probably you tried the PR under WIP. I will merge soon after CI passed and will release a new version. Could you try the latest branch again? 

If you have a problem in the latest branch, can you open a new issue with reproduction case? Thank you for reporting!

**Comment by muratmusic** [comment]
@kishikawakatsumi many thanks

I reported it as another issue about recalculating of contentSize. This issue is closed at the moment.

I plan to test this issue in nearest days with new master branch sources.

**Pull request merged**
