### PR TITLE
Update to swift 4.2

### PR DESCRIPTION
**Pull request by bikisDesign-zz**

### CODE REVIEW

**Comment by leedsalex** [comment]
@kishikawakatsumi Could you pull this in? It's required to build in the latest version of Xcode (10.2 w/ Swift 5)

**Comment by KimtiPatel** [comment]
@kishikawakatsumi  can u please provide framework update to support swift 5 , Xcode 11.2. We r currently blocked by this
Appreciate your time

Thanks

**Comment by KimtiPatel** [comment]
Hi @kishikawakatsumi ,
I tried creating Spreadsheet FW supporting swift 5 for both and simulator support as per below. 
/Desktop/SpreadsheetView.framework/SpreadsheetView are: i386 x86_64 armv7 arm64 
But it still don't work for phones. i have to add specific FW to build on each. Like for phone : if add FW with just "armv7 arm64", that builds fine..but not with all.
Any clue?

Please find FW in attachment:
[SpreadsheetView.framework.zip](https://github.com/kishikawakatsumi/SpreadsheetView/files/3920365/SpreadsheetView.framework.zip)


Could not find module 'SpreadsheetView' for target 'x86_64-apple-ios-simulator'; found: arm64, armv7-apple-ios, arm64-apple-ios, arm, armv7

**Comment by bannzai** [comment]
Done about up swift version to 5. I will release it. I close this PR. Thank you your contributions 👍 

https://github.com/bannzai/SpreadsheetView/pull/256

**Pull request closed without merging**
